quarkus.http.port=8081

smallrye.jwt.sign.key.location=../auth/privateKey.pem
mp.jwt.verify.publickey.location=../auth/publicKey.pem
mp.jwt.verify.issuer=auth-service
quarkus.log.category."io.smallrye.jwt".level=DEBUG

#Data source
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=fernando
quarkus.datasource.password=fernando
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pizzaplaza_db

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.persistence-xml.ignore=true
quarkus.hibernate-orm.active=true
quarkus.hibernate-orm.packages=br.com.pizzaplaza.entity
